### ISSUE TITLE
DERNA consistently crashes on certain amino acid sequences

### ISSUE THREAD

**Issue by h-ahl** [elkebir-group/derna#1]
Thanks for an excellent package.

My issue is as above. Certain amino acid sequences simply crash with an error of type
`[1]    132848 segmentation fault (core dumped)  ./derna -i ~/test.fasta -o out.txt -m 1 -s 1`

A partial output is written, e.g.

```
protein sequence: <my-sequence>

```

I have noticed that other amino acid sequences also crash, but only occasionally. 

I have tried building from source, as well as using DERNA through bioconda.

**Comment by xinyu-g** [comment]
Hi, sorry for the delayed response. Could you provide me the sequences that caused the issue?

**Comment by xinyu-g** [comment]
@h-ahl HI, I wanted to follow up on the issue. I understand that you may not be able to share the specific sequences due to data sensitivity, but could you provide some information on the length of the sequences you are using and the hardware (CPU/GPU) you are running derna on? It seems the crash might be related to an out-of-memory error.

**Comment by h-ahl** [comment]
Hi, @xinyu-g - thanks for following up on this. This was for very short sequences, about 10-30 amino acids in length. I ran on CPU. For such short sequences, I wouldn't expect any memory issues

**Comment by abegue-instadeep** [comment]
Hello! Thanks for looking into this. Here is a random example sequence I encountered this with: MPEPNKLDKHGARPGLWPVHVYML

**Comment by xinyu-g** [comment]
Would you mind sharing the crash message with me? I tested the sequence on my end and didn’t encounter a crash. I’ve attached my running log for reference—please let me know if you notice anything I may have overlooked. (The highlighted section at the send is running with the sequence you provided.) Also, please double-check that your repository is up to date. @abegue-instadeep 

[derna_debug_log.pdf](https://github.com/user-attachments/files/17541623/derna_debug_log.pdf)

**Comment by xinyu-g** [comment]
Hi, another user noted that the error doesn’t occur on a Mac, which is the system I was using as well. I’m switching to a different system now to investigate the issue further and locate the error. @abegue-instadeep

**Comment by xinyu-g** [comment]
Hi, I just pushed a commit to address the issue. Could you give it a test and let me know if it works on your end? (You may want to directly reclone the repository, as no new release has been created yet.) @h-ahl @abegue-instadeep

**Comment by abegue-instadeep** [comment]
It works for my toy example. I will let @h-ahl close the issue if it works for him too.

**Comment by h-ahl** [comment]
Thank you kindly!
