### ISSUE TITLE
bug: cannot pass codon tables

### ISSUE THREAD

**Issue by h-ahl** [elkebir-group/derna#2]
Hi! I'm trying to pass a codon table, but am getting issues like below:

```
╰─± ./build/derna -i data/input.fasta -o data/output.txt -c /home/hahl/derna/data/InputFiles/sample_codon_usage.csv -m 1 -s 2 -l 0.5
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stod
[1]    88748 IOT instruction (core dumped)  ./build/derna -i data/input.fasta -o data/output.txt -c  -m 1 -s 2 -l 0.5
```

As you can see, this happens for the sample table provided, which is meant to be the default values used as far as I'm aware. I'm attaching the input files below:
[inputs.zip](https://github.com/user-attachments/files/16360428/inputs.zip)

**Comment by xinyu-g** [comment]
Hi, my apologies again for the delayed response. Thank you for bringing the issue to our attention. The issue has been resolved in the latest release/commit of the repo.

**Comment by xinyu-g** [comment]
Closing the issue. Feel free to reopen or post another issue if needed.
