### ISSUE TITLE
Index out of bounds

### ISSUE THREAD

**Issue by Schlaubischlump** [elkebir-group/derna#4]
Hi @melkebir, 

I was debugging unexpected crashes of your program. While doing that, I encountered that your Zuker.cpp algorithm is running out of bounds, which causes unexpected behavior. In particular, Zuker.cpp line 86 says: `for (int a = 0; a < n; ++a)`.  `a` is then used in line 90 and 91 for `ava_nucleotides_int`, which in turn calls: `int pna = protein[a+1]` or `int ppa = protein[a-1]`. Both of these calls are undefined for `a=n-1` or `a=0`, respectively. You can easily reproduce this error by enforcing a runtime error instead of unexpected behavior if you run out of bounds. Vector has an [`.at`](https://cplusplus.com/reference/vector/vector/at/) method for this use case. So if you replace line 572 with `int pna = protein.at(a+1)` your program will reliable crash with an out of bounds error.

Since I don't know the inner workings of your algorithm, I'm not sure what the best fix is. Starting the index for `a` at `1` and ending at `n-1` will obviously prevent the problem, but I don't know if this is the correct behavior. 

After I apply this rudimentary fix the program crashes here: 

```
0x0000aaaaaaafa7b0 in Zuker::internal_CAI (this=0xfffffffff198, lambda=0.5, 
    a=113, b=115, i=0, j=1, x=0, y=0, la=339, lb=346, xi=0, yj=3)
    at /derna/src/Zuker.cpp:1055
1055	                    const int n_codon_dn = n_codon[pnd];
```

**Comment by xinyu-g** [comment]
Hi, thanks for bring up the issue. Could you share the sequence you are using as well to help me with the debug process? Thanks. @Schlaubischlump

**Comment by Schlaubischlump** [comment]
Thanks for your very, very quick reply!
I used a dummy sequence of 116 M letters. You can use the following docker file for debugging to reproduce the error: 

```
FROM public.ecr.aws/docker/library/python:3.12-slim as base

RUN apt-get update && apt-get upgrade -y && apt-get clean && apt-get -qq dist-upgrade
RUN apt-get -qq -y install --no-install-recommends apt-utils

RUN apt-get update
RUN apt-get -y install --no-install-recommends git cmake gcc build-essential gdb nano

RUN git -c http.sslVerify=false clone https://github.com/elkebir-group/derna.git

WORKDIR /derna

RUN mkdir build
WORKDIR build
RUN cmake -DCMAKE_BUILD_TYPE=DEBUG ..
RUN make

RUN echo ">116M\nMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM" > "inputM.fasta"

#RUN ./derna -i inputM.fasta -o output.txt -m 1 -s 2 -l 0.5
```

You can use the following commands to build the docker (from within the director that contains the `Dockerfile`) and then run and debug `derna: 

```
docker buildx build -t "derna:latest" .
docker run -it derna:latest /bin/bash
gdb ./derna
run -i inputM.fasta -o output.txt -m 1 -s 2 -l 0.5
```

This way you get debugging information as well.

**Comment by xinyu-g** [comment]
Thanks for sharing the sequence! I’ll try to get back to you later today if I can resolve the issue quickly. If not, I’ll follow up later this week after I finish with some deadlines.

**Comment by xinyu-g** [comment]
Hi, apologies for the delayed response—I was tied up with some deadlines. I tested the all-M sequence on my end in debug mode and didn’t encounter the same error (see the attached terminal log). However, please let me know if you spot anything in the log that I might have missed. @Schlaubischlump 
[derna_debug_log.pdf](https://github.com/user-attachments/files/17541571/derna_debug_log.pdf)

**Comment by Schlaubischlump** [comment]
Did you modify the algorithm to use the "at" method or use the docker image? 

The error is dependent on the memory layout. Thats means it is non deterministic in nature. It might or might not happen depending on the memory allocation of you machine. I saw you are using Apple Clang, so you probably executed it on your mac. On my mac, the bug also does not occur. But this is by pure luck.

**Comment by xinyu-g** [comment]
Thank you for pointing that out! I was able to reproduce the issue with the Docker image and will keep you updated.

**Comment by xinyu-g** [comment]
Hi, I just pushed a commit to address the issue. Could you give it a test and let me know if it works on your end? (If you’re rebuilding the Dockerfile, please make sure to clear the Docker build cache.) @Schlaubischlump

**Comment by xinyu-g** [comment]
Hi, I just wanted to follow up on the issue. Are you still experiencing error with the latest version? If not, I think I will close the issue soon. @Schlaubischlump

**Comment by Schlaubischlump** [comment]
Hi @xinyu-g, 

Sorry for the late reply! The issue seems to be fixed. Thank you for your quick bug fix, really appreciate it! I'll close the issue.
